# Generated by Django 3.1 on 2020-08-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200816_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(default=123123, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
