# Generated by Django 3.1 on 2020-08-18 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200818_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_users',
            field=models.ManyToManyField(blank=True, through='main.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
