# Generated by Django 3.1 on 2020-08-19 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200818_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(default='super user', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_users',
            field=models.ManyToManyField(blank=True, through='main.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
